Algoritmo "semnome"

Var
   Val: vetor[1..7] de inteIro
   I , ToTpar: inteiro


Inicio
      ToTpar <- 0
      Para i <- 1 ate 7 faca
           Escreva( "Digite o ", I,"o. valor")
           Leia(val[I       ])
                       Se (Val[I] % 2 = 0) entao
                       Totpar <- Totpar + 1
                       Fimse
      FimPara
      Escreva("o total de numeros pares é de", Totpar)
           
      
      
      
Fimalgoritmo